config/routes.rb
Rails.application.routes.draw do
  # User routes
  resources :profiles, only: [:show]
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/availability', to: 'registrations#availability', as: 'user_availability'
    put '/users/availability', to: 'registrations#update_availability'
  end

  resources :recommendations
  resources :student_applications
  
  get 'admins/dashboard', to: 'admins#dashboard', as: 'dashboard'
  put 'admins/verify_user/:id', to: 'admins#verify_user', as: 'verify_user'
  
  # Courses routes
  resources :courses do
    resources :sections, only: [:show, :new, :create, :edit, :update, :destroy]
    collection do
      post 'fetch_classes'
    end
  end
  
  delete 'clear_classes', to: 'courses#clear_classes', as: 'clear_classes'

  # Set root index
  root 'home#index'
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :course
  validate :student_email_exists

  private

  def student_email_exists
    unless User.exists?(email: student_email)
      errors.add(:student_email, "does not exist")
    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recommendation, only: %i[ show edit update destroy ]

  # GET /recommendations or /recommendations.json
  def index
    @recommendations = Recommendation.all
    @recommendations = @recommendations.where(course_id: params[:course_filter]) if params[:course_filter].present?
  end

  # GET /recommendations/1 or /recommendations/1.json
  def show
  end

  # GET /recommendations/new
  def new
    @recommendation = Recommendation.new
    @recommendation.prof_email = current_user.email
    @courses = Course.order(title: :asc)
  end

  # GET /recommendations/1/edit
  def edit
    @courses = Course.order(title: :asc)
    @sections = @recommendation.course.sections
  end

  # POST /recommendations or /recommendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)
    @recommendation.prof_email = current_user.email
  
    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to recommendation_url(@recommendation), notice: "Recommendation was successfully created." }
        format.json { render :show, status: :created, location: @recommendation }
      else
        @courses = Course.order(title: :asc)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end  

  # PATCH/PUT /recommendations/1 or /recommendations/1.json
  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to recommendation_url(@recommendation), notice: "Recommendation was successfully updated." }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1 or /recommendations/1.json
  def destroy
    @recommendation.destroy!

    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: "Recommendation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recommendation_params
      params.require(:recommendation).permit(:student_email, :course_id, :section_id, :reason)
    end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/edit.html.erb
<div class="card">
  <div class="card-header">
    <h3>Editing Recommendation</h3>
  </div>
  <div class="card-body">
    <%= form_with(model: @recommendation) do |form| %>
      <% if @recommendation.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

          <ul>
            <% @recommendation.errors.full_messages.each do |error_message| %>
              <li><%= error_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :student_email, class: "font-weight-bold" %>
        <%= form.text_field :student_email, class: "form-control", readonly: true %>
      </div>

      <div class="form-group">
        <%= form.label :course_title, class: "font-weight-bold" %>
        <%= form.text_field :course_title, class: "form-control", value: @recommendation.course.title, readonly: true %>
      </div>

      <div class="form-group">
        <%= form.label :section_id, class: "font-weight-bold" %>
        <%= form.collection_select :section_id, [OpenStruct.new(id: nil, section_number: "Select Section")] + @sections, :id, :section_number, { prompt: false }, { class: "form-control", id: "section-select" } %>
      </div>

      <div class="form-group">
        <%= form.label :reason, class: "font-weight-bold" %>
        <%= form.text_area :reason, class: "form-control", rows: 3 %>
      </div>

      <div>
        <%= form.submit "Save", class: "btn btn-success" %>
        <%= link_to "Back", recommendation_path(@recommendation), class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recommendations/index.html.erb
<div class="card mb-3">
  <div class="card-header"><h3>Recommendations</h3></div>
  <div class="card-body">
    <% if current_user.admin? %>
      <%= form_tag(recommendations_path, method: "get", class: "form-inline mb-3") do %>
        <div class="form-group d-flex">
          <%= select_tag "course_filter", options_from_collection_for_select(Course.order(title: :asc), :id, :title, params[:course_filter]), { prompt: "Select Course", class: "form-control" } %>
          <%= submit_tag "Search", class: "btn btn-primary" %>
        </div>
      <% end %>
      <%= link_to "Create Recommendation", new_recommendation_path, class: "btn btn-success" %>
      <br/><br/>

      <table class="table">
        <thead>
          <tr>
            <th>Student Email</th>
            <th>Professor Email</th>
            <th>Course</th>
            <th>Section</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @recommendations.each do |recommendation| %>
            <tr>
              <td><%= link_to recommendation.student_email, profile_path(User.find_by(email: recommendation.student_email)), class: "text-decoration-none" %></td>
              <td><%= link_to recommendation.prof_email, profile_path(User.find_by(email: recommendation.prof_email)), class: "text-decoration-none" %></td>
              <td><%= link_to Course.find(recommendation.course_id).title, course_path(recommendation.course_id), class: "text-decoration-none" %></td>
              <td>
                <% if recommendation.section_id %>
                  <%= link_to Section.find(recommendation.section_id).section_number, course_section_path(recommendation.course_id, recommendation.section_id), class: "text-decoration-none" %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td><%= button_to "Show", recommendation, method: :get, class: "btn-primary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% unless @recommendations.any? %>
        No recommendations found!
      <% end %>
    <% end %>
  </div>
</div>

app/views/recommendations/new.html.erb
<div class="card">
  <div class="card-header">
    <h3>New Recommendation</h3>
  </div>

  <div class="card-body">
    <%= form_with(model: @recommendation) do |form| %>
      <% if @recommendation.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

          <ul>
            <% @recommendation.errors.full_messages.each do |error_message| %>
              <li><%= error_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :student_email, class: "font-weight-bold" %>
        <%= form.text_field :student_email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :course_id, class: "font-weight-bold" %>
        <%= form.collection_select :course_id, @courses, :id, :title, { include_blank: "Select Course" }, { class: "form-control", id: "course-select" } %>
      </div>

      <div class="form-group">
        <%= form.label :reason, class: "font-weight-bold" %>
        <%= form.text_area :reason, class: "form-control", rows: 3 %>
      </div>

      <div>
        <%= form.submit "Submit", class: "btn btn-success" %>
        <%= link_to "Back", recommendations_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recommendations/show.html.erb
<div class="card">
  <div class="card-header">
    <h3>Recommendation</h3>
  </div>

  <div class="card-body">

    <div id="<%= dom_id @recommendation %>">
      <p class="card-text">
        <strong>Student email:</strong>
        <%= link_to @recommendation.student_email, profile_path(User.find_by(email: @recommendation.student_email)), class: "text-decoration-none" %>
      </p>

      <p class="card-text">
        <strong>Professor email:</strong>
        <%= link_to @recommendation.prof_email, profile_path(User.find_by(email: @recommendation.prof_email)), class: "text-decoration-none" %>
      </p>

      <p class="card-text">
        <strong>Info:</strong>
        <% if @recommendation.reason.present? %>
          <%= @recommendation.reason %>
        <% else %>
          <span>No reason given.</span>
        <% end %>
      </p>

      <p class="card-text">
        <strong>Course:</strong>
          <%= link_to Course.find(@recommendation.course_id).title, course_path(@recommendation.course), class: "text-decoration-none" %>
      </p>

      <p class="card-text">
        <strong>Section:</strong>
        <% if @recommendation.section_id.present? %>
          <% section = Section.find(@recommendation.section_id) %>
          <%= link_to section.section_number, course_section_path(section.course, section), class: "text-decoration-none" %>
        <% else %>
          <span>N/A</span>
        <% end %>
      </p>
    </div>

    <div class="mt-3">
      <%= link_to "Edit", edit_recommendation_path(@recommendation), class: "btn btn-primary mr-2" %>
      <%= link_to "Back", recommendations_path, class: "btn btn-secondary mr-2" %>
      <%= button_to "Delete", @recommendation, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", form_class: "d-inline" %>
    </div>
  </div>
</div>