config/routes.rb
Rails.application.routes.draw do
  # User routes
  resources :profiles, only: [:show]
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/availability', to: 'registrations#availability', as: 'user_availability'
    put '/users/availability', to: 'registrations#update_availability'
  end

  resources :recommendations
  resources :student_applications
  
  get 'admins/dashboard', to: 'admins#dashboard', as: 'dashboard'
  put 'admins/verify_user/:id', to: 'admins#verify_user', as: 'verify_user'
  
  # Courses routes
  resources :courses do
    resources :sections, only: [:show, :new, :create, :edit, :update, :destroy]
    collection do
      post 'fetch_classes'
    end
  end
  
  delete 'clear_classes', to: 'courses#clear_classes', as: 'clear_classes'

  # Set root index
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Course Catalog', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <!-- User is signed in -->
        <% if user_signed_in? %>
          <!-- Include Student Applications link -->
          <% if current_user.admin? || current_user.role == 'student' %>
            <li class="nav-item">
              <%= link_to "Applications", student_applications_path, class:"nav-link" %>
            </li>
          <% end %>

          <!-- Visible to every user -->
          <li class="nav-item">
            <%= link_to "Catalog", courses_path, class:"nav-link" %>
          </li>
          
          <!-- Only visible to admins -->
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Dashboard", dashboard_path, class:"nav-link" %>
            </li>
          <% end %>
          
          <!-- Only visible to admins or instructors -->
          <% if current_user.admin? || current_user.instructor? %>
            <li class="nav-item">
              <%= link_to "Recommendations", recommendations_path, class:"nav-link" %>
            </li>
          <% end %>

          <!-- Visible to every user -->
          <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class:"nav-link" %>
          </li>
        <!-- User is not signed in -->
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homepage</title>
  </head>
  <body>
    <div class="container">
      <h1 class="text-center mt-3">Welcome to our CSE 3901 Rails Project!</h1>
      <% if user_signed_in? %>
        <h3 class="text-center mt-3">Hello, <%= current_user.email %>!</h3>
      <% else %>
        <h3 class="text-center mt-3">Please <%= link_to 'login', new_user_session_path %> to continue.</h3>
      <% end %>

      <% if !current_user.nil? && !current_user.verified %>
        <h3 class="text-center text-danger mt-3">Please ask an admin to verify your account!</h3>
      <% end %>
    </div>
  </body>
</html>