config/routes.rb
Rails.application.routes.draw do
  # User routes
  resources :profiles, only: [:show]
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/availability', to: 'registrations#availability', as: 'user_availability'
    put '/users/availability', to: 'registrations#update_availability'
  end

  resources :recommendations
  resources :student_applications
  
  get 'admins/dashboard', to: 'admins#dashboard', as: 'dashboard'
  put 'admins/verify_user/:id', to: 'admins#verify_user', as: 'verify_user'
  
  # Courses routes
  resources :courses do
    resources :sections, only: [:show, :new, :create, :edit, :update, :destroy]
    collection do
      post 'fetch_classes'
    end
  end
  
  delete 'clear_classes', to: 'courses#clear_classes', as: 'clear_classes'

  # Set root index
  root 'home#index'
end

app/models/student_application.rb
class StudentApplication < ApplicationRecord
  # Associations
  belongs_to :user
  has_and_belongs_to_many :courses

  # Validations
  validates :user_id, :contact_info, :status, :course_id, presence: true
  validates :status, inclusion: { in: %w[pending approved denied] }
  validates :preferences_in_grading_assignments, length: { maximum: 500 }, allow_blank: true

  # Callbacks
  after_initialize :init_values

  private

  # Sets initial values for 'status'
  def init_values
    self.status ||= 'pending'
  end
end

app/controllers/student_applications_controller.rb
class StudentApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student_application, only: [:show, :edit, :update, :destroy]
  before_action :authorize_access, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :application_not_found

  def index
    @student_applications = current_user.admin? ? StudentApplication.all : StudentApplication.where(user_id: current_user.id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_applications }
    end
  end

  def show
    @student_application = StudentApplication.find(params[:id])
    user = @student_application.user
    @recommendations = Recommendation.where(student_email: user.email, course_id: @student_application.course_id)
    @sections = Course.find(@student_application.course_id).sections
  end

  def new
    @student_application = StudentApplication.new
    @courses = Course.order(title: :asc)
  end

  def edit
    @courses = Course.order(title: :asc)
  end

  def create
    @student_application = StudentApplication.new(student_application_params)
    @student_application.user = current_user

    respond_to do |format|
      if @student_application.save
        format.html { redirect_to @student_application, notice: "Studen application was successfully created." }
        format.json { render :show, status: :created, location: @student_application }
      else
        @courses = Course.order(title: :asc)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_application.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      status = student_application_params[:status]
      
      if status == 'approved'
        @course = Course.find(@student_application.course_id)
        @user = @student_application.user
        @section = Section.find(params[:section_id])

        if @section.required_graders <= 0
          flash[:error] = "This section does not need any more graders!"
          redirect_to action: :show
          return
        end

        unless @section.blank?
          @student_application.user.sections << @section
          @section.required_graders -= 1
          @section.save!
        else
          flash[:error] = "Please select a valid section!"
          redirect_to action: :show
          return
        end
      elsif status == 'denied'
        @student_application.user.sections.each do |section|
          if @course.sections.include?(section)
            @user.sections.delete(section)
            section.required_graders += 1
            @section.save!
          end
        end
      end
      
      if @student_application.update(student_application_params)
        format.html { redirect_to @student_application, notice: "Student application was successfully updated." }
        format.json { render :show, status: :ok, location: @student_application }
      else
        @courses = Course.order(title: :asc)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_application.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def destroy
    @student_application.destroy
    respond_to do |format|
      format.html { redirect_to student_applications_url, notice: 'Student application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_student_application
    @student_application = StudentApplication.find(params[:id])
  end

  def student_application_params
    params.require(:student_application).permit(:status, :contact_info, :preferences_in_grading_assignments, :course_id)
  end

  def authorize_access
    unless current_user.admin? || @student_application.user == current_user
      flash[:alert] = 'You are not authorized to view or edit this application.'
      redirect_to root_url
    end
  end

  def application_not_found
    flash[:alert] = "Application not found."
    redirect_to student_applications_path
  end

  def authorize_admin
    unless current_user.admin?
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_to root_url
    end
  end
end

app/helpers/student_applications_helper.rb
module StudentApplicationsHelper
end

app/views/student_applications/_form.html.erb
<%= form_with(model: @student_application, local: true, class: "mt-4", id: "studentApplicationForm") do |form| %>
  <% if @student_application.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@student_application.errors.count, "error") %> prohibited this application from being saved:</h2>
      <ul>
      <% @student_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :contact_info, class: "font-weight-bold" %>
    <%= form.text_field :contact_info, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :course_id, class: "font-weight-bold" %>
    <%= form.collection_select :course_id, @courses, :id, :title, { include_blank: "Select Course" }, { class: "form-control", id: "course-select" } %>
  </div>

  <div class="form-group">
    <%= form.label :preferences_in_grading_assignments, "Preference in Grading Assignments", class: "font-weight-bold" %>
    <%= form.text_area :preferences_in_grading_assignments, class: "form-control", rows: 5 %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/student_applications/edit.html.erb
<div class="card">
  <div class="card-header">
    <h3>Editing Student Application</h3>
  </div>
  <div class="card-body">
    <%= render 'form', student_application: @student_application %>
    <hr>
    <%= link_to 'Back to List', student_applications_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/student_applications/index.html.erb
<div class="card mb-3">
  <div class="card-header"><h3>Student Applications</h3></div>
  <div class="card-body">
    <% if @student_applications.any? %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">User</th>
            <th scope="col">Contact Info</th>
            <th scope="col">Course</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @student_applications.each do |application| %>
            <tr>
              <td><%= link_to application.user.email, profile_path(User.find_by(email: application.user.email)), class: "text-decoration-none" %></td>
              <td><%= application.contact_info %></td>
              <td><%= link_to Course.find(application.course_id).title, course_path(application.course_id), class: "text-decoration-none" %></td>
              <td><%= application.status %></td>
              <td>
                <%= link_to 'Show', student_application_path(application), class: "btn btn-primary" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No student applications available.</p>
    <% end %>
    <%= link_to 'New Application', new_student_application_path, class: "btn btn-success" %>
  </div>
</div>

app/views/student_applications/new.html.erb
<div class="card mb-3">
  <div class="card-header">
    <h3>New Student Application</h3>
  </div>
  <div class="card-body">
    <%= render 'form', student_application: @student_application %>
    <hr>
    <%= link_to 'Back to List', student_applications_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/student_applications/show.html.erb
<div class="card mb-3">
  <div class="card-header">
    <h3>Student Application Details</h3>
  </div>
  <div class="card-body">
    <% if flash[:error] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>

    <p><strong>Contact Info:</strong> <%= @student_application.contact_info %></p>
    <p><strong>Course:</strong> <%= link_to Course.find(@student_application.course_id).title, course_path(@student_application.course_id), class: "text-decoration-none" %></p>
    
    <div class="mb-3">
      <strong>Status:</strong> <%= @student_application.status %><br/>
      <% if current_user.admin? %>
        <% if @student_application.status != 'approved' %>
          <div class="d-inline-block">
            <%= form_with(model: @student_application, local: true) do |form| %>
              <%= select_tag :section_id, options_for_select([["Select Section", nil]] + @sections.map { |section| ["#{section.section_number} (Graders Needed: #{section.required_graders})", section.id] }), id: "section-select" %>

              <%= form.hidden_field :status, value: "approved" %>
              <%= form.submit 'Approve', class: 'btn-success mr-1' %>
            <% end %>
          </div>
        <% end %>

        <div class="d-inline-block">
          <%= form_with(model: @student_application, local: true) do |form| %>
            <%= form.hidden_field :status, value: "denied" %>
            <% if @student_application.status == 'approved' %>
              <%= form.submit 'End', class: 'btn-danger mr-1' %>
            <% elsif @student_application.status != 'denied' %>
              <%= form.submit 'Deny', class: 'btn-danger mr-1' %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div>
      <strong>Reason/Preference:</strong>
      <%= @student_application.preferences_in_grading_assignments %>
    </div>

    <!-- Links to all recommendations belonging to the owner of the application -->
    <div class="mt-3">
      <strong>Recommendations:</strong>
      <% if @recommendations.any? %>
        <ul>
          <% @recommendations.each do |recommendation| %>
            <% if recommendation.section_id %>
              <li><%= link_to "From #{recommendation.prof_email} for section #{Section.find(recommendation.section_id).section_number}", recommendation %></li>
            <% else %>
              <li><%= link_to "From #{recommendation.prof_email} (No section specified)", recommendation %></li>
            <% end %>
          <% end %>
        </ul>
      <% else %>
        <p>No recommendations for selected courses!</p>
      <% end %>
    </div>

    <hr>

    <!-- Buttons for editing and navigating back -->
    <div class="mt-3">
      <%= link_to 'Edit', edit_student_application_path(@student_application), class: "btn btn-primary mr-2" %>
      <%= link_to 'Back to List', student_applications_path, class: "btn btn-secondary mr-2" %>
    </div>
  </div>
</div>